/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tr_cohort_job_matching;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {

    public static void main(String[] args) {

        final App app = new App();
        final String[] candidateList = new String[]{"Java", "Spring"};
        final String[] roleList = new String[]{"Java"};

        System.out.println("Candidate role match score is: " + app.countMatch(candidateList, roleList));
    }

    public int countMatch(String[] candidateList, String[] roleList) {
        final List<String> list1 = new ArrayList(Arrays.asList(candidateList));
        final List<String> list2 = Arrays.asList(roleList);
        list1.retainAll(list2);
        final int matches = list1.size();

        return roleList.length / matches * 100;
    }
}
